<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../MagicalCryptoWallet.Fluent/MagicalCryptoWallet.Fluent.csproj" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="QRackers" PrivateAssets="all" />
  </ItemGroup>
</Project>
