blank_issues_enabled: false
contact_links:
  - name: 📃 User documentation
    url: https://github.com/nopara73/MagicalCryptoWallet/blob/master/MagicalCryptoWallet.Documentation/README.md
    about: Search for any information about MagicalCryptoWallet.
  - name: 💪 Community support
    url: https://github.com/nopara73/MagicalCryptoWallet/discussions/categories/support
    about: Feel free to ask anything.
  - name: ❓ Other issue?
    url: https://github.com/nopara73/MagicalCryptoWallet/discussions/
    about: Search on the community forum.
