"""Copy pinned real Core/Client source and apply the review patch only in a snapshot."""
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess


def git(root, *args):
    return subprocess.run(["git", "-C", str(root), *args], check=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE).stdout


def prepare(root, snapshot):
    scopes = ["MagicalCryptoWallet", "MagicalCryptoWallet.Client", "ThirdParty/WabiSabi",
        "mcw", "Directory.Build.props", "Directory.Build.targets", "Directory.Packages.props",
        "global.json", "BannedSymbols.txt", ".editorconfig",
        "MagicalCryptoWallet.Tests/UnitTests/SingleWalletTests.cs",
        "MagicalCryptoWallet.Tests/UnitTests/Services/CompactFilterBehaviorTests.cs",
        "MagicalCryptoWallet.Tests/UnitTests/Wallet/FilterProcessor/BlockFilterIteratorTests.cs",
        "MagicalCryptoWallet.Tests/UnitTests/Mocks/TestableFilterStore.cs",
        "MagicalCryptoWallet.Tests/Helpers/Common.cs"]
    git(root, "diff", "--exit-code", "HEAD", "--", *scopes)
    pin = git(root, "rev-parse", "HEAD").decode().strip()
    names = git(root, "ls-files", "-z", "--", *scopes).decode().split("\0")
    snapshot.mkdir(parents=True, exist_ok=False)
    manifest = []
    for name in filter(None, names):
        # Bundled executables/geoip are packaging inputs; no bundled process is
        # launched by this matching-only snapshot. Do not copy large binaries.
        if name.startswith("MagicalCryptoWallet/BundledApps/Binaries/") or name.startswith("MagicalCryptoWallet/Tor/Geoip/"):
            continue
        source = root / name
        if not source.is_file():
            raise ValueError("Unexpected non-file tracked source: " + name)
        target = snapshot / name
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
        digest = hashlib.sha256(source.read_bytes()).hexdigest()
        assert hashlib.sha256(target.read_bytes()).hexdigest() == digest
        manifest.append(dict(path=name, sha256=digest))
    patch = root / "mcw/tests/compact_filters_host_wiring.patch"
    for extra in ["mcw/tests/compact_filters_caller_probe.inc"]:
        target = snapshot / extra
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(root / extra, target)
    for args in [["--check"], []]:
        subprocess.run(["git", "-C", str(snapshot), "apply", "--no-index", "--ignore-space-change", "--whitespace=nowarn",
            *args, str(patch)], check=True)
    caller = snapshot / "MagicalCryptoWallet/Wallets/WalletFilterProcessor.cs"
    caller_text = caller.read_text()
    assert "filter.Filter.MatchAny(" not in caller_text
    assert caller_text.count("McwCompactFilterMatcher.MatchAnyAsync(") == 1
    probe = snapshot / "caller-probe"
    probe.mkdir()
    shutil.copyfile(root / "mcw/tests/compact_filters_caller_probe.inc", probe / "Program.cs")
    linked = ["UnitTests/SingleWalletTests.cs", "UnitTests/Services/CompactFilterBehaviorTests.cs",
        "UnitTests/Wallet/FilterProcessor/BlockFilterIteratorTests.cs",
        "UnitTests/Mocks/TestableFilterStore.cs", "Helpers/Common.cs"]
    project = '''<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><AssemblyName>MagicalCryptoWallet.Tests</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings><XunitAutoGeneratedEntryPoint>false</XunitAutoGeneratedEntryPoint>
    <NoWarn>1701;1702;1705;1591;CA1031;CA1822</NoWarn><BuildMcwHost>false</BuildMcwHost>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../MagicalCryptoWallet.Client/MagicalCryptoWallet.Client.csproj" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
'''
    project += "".join(f'    <Compile Include="../MagicalCryptoWallet.Tests/{name}" Link="Retained/{name}" />\n' for name in linked)
    project += "  </ItemGroup>\n</Project>\n"
    (probe / "CallerProbe.csproj").write_text(project, encoding="utf-8", newline="\n")
    (snapshot / "NuGet.Config").write_text("<configuration><packageSources><clear /></packageSources></configuration>", encoding="utf-8")
    evidence = dict(source_pin=pin, copied_source_files=manifest,
        patched_caller_sha256=hashlib.sha256(caller.read_bytes()).hexdigest(),
        patched_adapter_sha256=hashlib.sha256((snapshot / "MagicalCryptoWallet/Mcw/CompactFilters/McwCompactFilterMatcher.cs").read_bytes()).hexdigest(),
        patch_sha256_canonical_lf=hashlib.sha256(patch.read_bytes().replace(b"\r\n", b"\n")).hexdigest(),
        snapshot=str(snapshot), source_scope="actual complete Core and Client projects plus retained synthetic test sources")
    (snapshot / "caller-source-manifest.json").write_text(json.dumps(evidence, indent=2), encoding="utf-8", newline="\n")
    print(f"Prepared pinned real Core/Client snapshot at {pin}: {len(manifest)} source files; actual caller patch applied only there.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--snapshot", type=Path, required=True)
    args = parser.parse_args()
    prepare(args.root.resolve(), args.snapshot.resolve())
