"""Extract normative RFC7932 data, not implementation code. stdlib only."""
import argparse
import ast
import hashlib
import json
import pathlib
import re
import zlib

parser = argparse.ArgumentParser()
parser.add_argument("--rfc", required=True)
args = parser.parse_args()
source = pathlib.Path(args.rfc).read_bytes()
text = source.decode("ascii")
data_root = pathlib.Path(__file__).resolve().parents[1] / "src/content_service/data"
data_root.mkdir(parents=True, exist_ok=True)
a = text.split("\nAppendix A.  Static Dictionary Data", 1)[1].split("\nAppendix B.", 1)[0]
dictionary = bytes.fromhex("".join(re.findall(r"^\s{6}([0-9a-f]{2,64})\s*$", a, re.MULTILINE)))
assert len(dictionary) == 122784 and zlib.crc32(dictionary) == 0x5136cb04
(data_root / "dictionary.bin").write_bytes(dictionary)
nbits_text = a.split("NDBITS :=", 1)[1]
nbits = [int(v) for v in re.findall(r"\d+", nbits_text)]
assert len(nbits) == 25
offsets = []
at = 0
for length, bits in enumerate(nbits):
    offsets.append(at)
    if length >= 4:
        at += length * (1 << bits)
assert at == len(dictionary)
tables = []
for n, expected in enumerate((0x8e91efb7, 0xd01a32f4, 0x0dd7a0d6)):
    part = text.split(f"Lut{n} :=", 1)[1]
    part = part.split(f"Lut{n+1} :=", 1)[0] if n < 2 else part.split("The lengths and the CRC-32", 1)[0]
    rows = [row for row in part.splitlines() if re.fullmatch(r"[\s\d,]+", row) and "," in row]
    values = [int(v) for row in rows for v in re.findall(r"\d+", row)]
    assert len(values) == 256 and zlib.crc32(bytes(values)) == expected
    tables.append(values)
b = text.split("\nAppendix B.  List of Word Transformations", 1)[1].split("\nAppendix C.", 1)[0]
pattern = r'^\s+(\d+)\s+("(?:[^"\\]|\\.)*")\s+(\w+)\s+("(?:[^"\\]|\\.)*")\s*$'
transforms = []
serialized = bytearray()
for match in re.finditer(pattern, b, re.MULTILINE):
    index, prefix, operation, suffix = match.groups()
    assert int(index) == len(transforms)
    prefix = ast.literal_eval(prefix).encode("latin1")
    suffix = ast.literal_eval(suffix).encode("latin1")
    kind = {"Identity": 0, "FermentFirst": 1, "FermentAll": 2}.get(operation)
    if kind is None:
        kind = int(operation[-1]) + (2 if operation.startswith("OmitFirst") else 11)
    transforms.append((prefix, kind, suffix))
    serialized.extend(prefix + b"\0" + bytes([kind]) + suffix + b"\0")
assert len(transforms) == 121 and len(serialized) == 648 and zlib.crc32(serialized) == 0x3d965f81

def byte_literal(data):
    return 'b"' + "".join(f"\\x{v:02x}" for v in data) + '"'

output = ["// Normative RFC7932 data; regenerated by compression_brotli_tables.py.",
          "// See PROVENANCE.md and RFC-DATA-LICENSE for origin and license."]
for name, values in [("NDBITS", nbits), ("DOFFSET", offsets)] + [(f"LUT{n}", values) for n, values in enumerate(tables)]:
    kind = "usize" if name == "DOFFSET" else "u8"
    output.append(f"pub(super) const {name}: [{kind}; {len(values)}] = [")
    for start in range(0, len(values), 16):
        output.append("    " + ", ".join(map(str, values[start:start+16])) + ",")
    output.append("];")
output.append("pub(super) const TRANSFORMS: [super::Transform; 121] = [")
for prefix, kind, suffix in transforms:
    output.append(f"    super::Transform {{ prefix: {byte_literal(prefix)}, kind: {kind}, suffix: {byte_literal(suffix)} }},")
output.append("];")
(data_root / "tables.rs").write_text("\n".join(output) + "\n", encoding="utf-8", newline="\n")
report = dict(source_url="https://www.rfc-editor.org/rfc/rfc7932.txt",
              source_sha256=hashlib.sha256(source).hexdigest(), dictionary_bytes=len(dictionary),
              dictionary_sha256=hashlib.sha256(dictionary).hexdigest(), dictionary_crc32="5136cb04",
              tables_sha256=hashlib.sha256((data_root / "tables.rs").read_bytes()).hexdigest(),
              transform_count=len(transforms), transform_bytes=len(serialized), transform_crc32="3d965f81",
              lookup_crc32=["8e91efb7", "d01a32f4", "0dd7a0d6"], implementation_code_copied=False)
(data_root / "manifest.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8", newline="\n")
print(json.dumps(report, indent=2))
