// Independent, synthetic NBitcoin 10.0.13 reference. Test tooling only.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using NBitcoin;

public static class PsbtMetadataReference
{
	private static readonly Network Net = Network.Main;
	private static void Blob(BinaryWriter writer, byte[] bytes) { writer.Write(bytes.Length); writer.Write(bytes); }
	public static string[] Generate()
	{
		var rows = new List<string> { "# Synthetic metadata fixtures generated by the retained NBitcoin 10.0.13 implementation.", "# name<TAB>native-enrich-request-hex<TAB>legacy-result-hex" };
		foreach (string name in new[] { "standard", "smart-off", "missing-parent", "no-fingerprint", "parent-only", "existing-parent", "bad-existing-parent", "finalized", "partial-finalized", "overwrite-origin", "v2", "witness-parent", "large-parent", "unrelated-outputs" })
		{
			byte[] secret1 = new byte[32]; secret1[31] = 1;
			byte[] secret2 = new byte[32]; secret2[31] = 2;
			using var key1 = new Key(secret1);
			using var key2 = new Key(secret2);
			PubKey pub = key1.PubKey, other = key2.PubKey;
			Script wpkh = pub.WitHash.ScriptPubKey;
			Script multi = PayToMultiSigTemplate.Instance.GenerateScriptPubKey(1, pub, other);
			var parent = Transaction.Create(Net);
			parent.Inputs.Add(new TxIn(new OutPoint(new uint256(17), 2)));
			parent.Outputs.Add(new TxOut(Money.Satoshis(100000), wpkh));
			parent.Outputs.Add(new TxOut(Money.Satoshis(100000), other.WitHash.ScriptPubKey));
			if (name == "witness-parent") { parent.Inputs[0].WitScript = new WitScript(new[] { new byte[] { 1, 2, 3 } }); }
			if (name == "large-parent") { parent.Inputs[0].ScriptSig = new Script(new byte[1100000]); }
			var transaction = Transaction.Create(Net);
			transaction.Inputs.Add(new TxIn(new OutPoint(parent, 0)));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(10000), wpkh));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(10000), pub.Hash.ScriptPubKey));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(10000), pub.ScriptPubKey));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(10000), pub.Decompress().ScriptPubKey));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(10000), multi));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(1000), wpkh.Hash.ScriptPubKey));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(1000), pub.ScriptPubKey.Hash.ScriptPubKey));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(1000), pub.ScriptPubKey.WitHash.ScriptPubKey));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(1000), multi.WitHash.ScriptPubKey.Hash.ScriptPubKey));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(1000), pub.ScriptPubKey.WitHash.ScriptPubKey));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(1000), wpkh.Hash.ScriptPubKey));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(1000), pub.GetScriptPubKey(ScriptPubKeyType.TaprootBIP86)));
			transaction.Outputs.Add(new TxOut(Money.Satoshis(1000), other.WitHash.ScriptPubKey));
			if (name == "unrelated-outputs")
			{
				transaction.Outputs.Clear();
				transaction.Outputs.Add(new TxOut(Money.Satoshis(90000), new Script("OP_TRUE")));
			}
			if (name == "partial-finalized") { transaction.Inputs.Add(new TxIn(new OutPoint(parent, 1))); }
			var packet = PSBT.FromTransaction(transaction, Net, name == "v2" ? PSBTVersion.PSBTv2 : PSBTVersion.PSBTv0);
			packet.Settings.IsSmart = name != "smart-off";
			foreach (var input in packet.Inputs) { input.WitnessUtxo = parent.Outputs[input.PrevOut.N]; }
			if (name == "parent-only" || name == "existing-parent") { packet.Inputs[0].WitnessUtxo = null; }
			if (name == "existing-parent") { packet.Inputs[0].NonWitnessUtxo = parent; }
			if (name == "bad-existing-parent")
			{
				var wrong = parent.Clone(); wrong.LockTime = new LockTime(10);
				packet.Inputs[0].NonWitnessUtxo = wrong;
			}
			if (name == "finalized" || name == "partial-finalized") { packet.Inputs[0].FinalScriptSig = new Script("OP_0"); }
			var fingerprint = new HDFingerprint(new byte[] { 1, 2, 3, 4 });
			var path = new RootedKeyPath(fingerprint, new KeyPath("84'/0'/0'/1/7"));
			if (name == "overwrite-origin") { packet.Inputs[0].HDKeyPaths.Add(pub, new RootedKeyPath(fingerprint, new KeyPath("1"))); }
			if (packet.Outputs.Count > 10)
			{
				packet.Outputs[7].WitnessScript = pub.ScriptPubKey;
				packet.Outputs[8].RedeemScript = multi.WitHash.ScriptPubKey;
				packet.Outputs[8].WitnessScript = multi;
				packet.Outputs[9].WitnessScript = other.ScriptPubKey;
				packet.Outputs[10].RedeemScript = other.WitHash.ScriptPubKey;
			}
			byte[] proprietary = { 0xfc, 3, (byte)'m', (byte)'c', (byte)'w', 1, 9 };
			packet.Unknown.Add(proprietary, new byte[] { 77, 0, 255 });
			foreach (var input in packet.Inputs) { input.Unknown.Add(proprietary, new byte[] { 8, 9, 10 }); }
			foreach (var output in packet.Outputs) { output.Unknown.Add(proprietary, new byte[] { 11, 12, 13 }); }
			var originals = packet.ToBytes();
			var associations = new List<(PubKey Pub, Script Script)>();
			if (name != "no-fingerprint")
			{
				foreach (var script in packet.Inputs.Select(input => input.WitnessUtxo?.ScriptPubKey).Concat(packet.Outputs.Select(output => output.ScriptPubKey)))
				{
					if (script == null) { continue; }
					foreach (var publicKey in new[] { pub, other })
					{
						if (script != publicKey.WitHash.ScriptPubKey && script != publicKey.GetScriptPubKey(ScriptPubKeyType.TaprootBIP86)) { continue; }
						associations.Add((publicKey, script));
						packet.AddKeyPath(publicKey, path, script);
					}
				}
			}
			bool addParent = name != "missing-parent";
			if (addParent) { foreach (var input in packet.Inputs) { input.NonWitnessUtxo = parent; } }
			using var request = new MemoryStream();
			using var writer = new BinaryWriter(request);
			writer.Write((ushort)1); Blob(writer, originals); writer.Write(packet.Settings.IsSmart);
			writer.Write(associations.Count);
			foreach (var association in associations)
			{
				writer.Write(association.Pub.ToBytes()); writer.Write(fingerprint.ToBytes());
				writer.Write(path.KeyPath.Indexes.Length);
				foreach (var index in path.KeyPath.Indexes) { writer.Write(index); }
				Blob(writer, association.Script.ToBytes());
			}
			writer.Write(addParent ? 1 : 0);
			if (addParent) { writer.Write(parent.GetHash().ToBytes()); Blob(writer, parent.ToBytes()); }
			rows.Add(name + "\t" + Convert.ToHexString(request.ToArray()).ToLowerInvariant() + "\t" + Convert.ToHexString(packet.ToBytes()).ToLowerInvariant());
		}
		return rows.ToArray();
	}
}
