"""Regenerate QR character mapping *data*, not decoder implementation.

Python's built-in codecs are a development-only mapping oracle. No Python,
codec package, library, executable or generator is included in the application.
The resulting Unicode maps are format data used by the first-party Rust parser.
Run with Python 3.14 from repository root; review the resulting source diff.
"""
from pathlib import Path
import hashlib
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'src/scan_service/charset_data.rs'

def scalar(data, codec):
    try:
        text = bytes(data).decode(codec, 'strict')
        return ord(text) if len(text) == 1 else 0xffffffff
    except UnicodeError:
        return 0xffffffff

tables = {}
for codec in ['cp437'] + [f'iso8859_{i}' for i in range(1, 17) if i != 12] + [f'cp125{i}' for i in [0,1,2,6]]:
    tables[codec.upper()] = [scalar([b], codec) for b in range(256)]
tables['SJIS'] = [scalar([a, b], 'shift_jis') for a in list(range(0x81, 0xa0)) + list(range(0xe0, 0xfd))
                  for b in list(range(0x40, 0x7f)) + list(range(0x80, 0xfd))]
tables['BIG5'] = [scalar([a, b], 'big5') for a in range(0x81, 0xff)
                  for b in list(range(0x40, 0x7f)) + list(range(0xa1, 0xff))]
tables['GB18030'] = [scalar([a, b], 'gb18030') for a in range(0x81, 0xff)
                     for b in list(range(0x40, 0x7f)) + list(range(0x80, 0xff))]
tables['EUC_KR'] = [scalar([a, b], 'euc_kr') for a in range(0xa1, 0xff) for b in range(0xa1, 0xff)]

# Compress the GB18030 four-byte pointer -> Unicode map into monotone runs.
# The pointer formula is specified by GB18030, and the decode lookup is ours.
ranges = []
start = last = value_start = value_last = None
for p in range(126 * 10 * 126 * 10):
    n = p
    d = n % 10 + 0x30; n //= 10
    c = n % 126 + 0x81; n //= 126
    b = n % 10 + 0x30; n //= 10
    a = n + 0x81
    value = scalar([a, b, c, d], 'gb18030')
    if value != 0xffffffff:
        if start is None:
            start = last = p; value_start = value_last = value
        elif p == last + 1 and value == value_last + 1:
            last = p; value_last = value
        else:
            ranges.append((start, last, value_start))
            start = last = p; value_start = value_last = value
    elif start is not None:
        ranges.append((start, last, value_start)); start = None
if start is not None:
    ranges.append((start, last, value_start))

source = ['//! Unicode character maps; generated by qr_scanning_charset_tables.py.',
          '//! Python built-in codecs supply mapping data only. No external implementation.',
          '#![allow(clippy::unreadable_literal)]']
for name, values in tables.items():
    source.append(f'pub(super) static {name}: [u32; {len(values)}] = [')
    source += ['    ' + ','.join(f'0x{v:x}' for v in values[i:i+16]) + ',' for i in range(0, len(values), 16)]
    source.append('];')
source.append(f'pub(super) static GB_RANGES: [(u32,u32,u32); {len(ranges)}] = [')
source += [f'    ({a},{b},0x{v:x}),' for a,b,v in ranges]
source.append('];')
OUT.write_text('\n'.join(source) + '\n', encoding='utf-8', newline='\n')
print(json.dumps(dict(python=sys.version, output=str(OUT), sha256=hashlib.sha256(OUT.read_bytes()).hexdigest(),
                      tables={k: len(v) for k,v in tables.items()}, gb_ranges=len(ranges)), indent=2))
