<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
		<NoWarn>1701;1702;1705;1591;1573;CA1031;CA1822</NoWarn>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
		<RuntimeIdentifiers>win-x64;linux-x64;linux-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputType>WinExe</OutputType>
	</PropertyGroup>

	<PropertyGroup>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyTitle>Magical Crypto Wallet</AssemblyTitle>
		<Description>
			Open-source, non-custodial, privacy focused Bitcoin wallet for Windows, Linux, and Mac. Built-in Tor, coinjoin and payjoin features.
		</Description>
		<Copyright>MIT</Copyright>
		<PackageTags>bitcoin-wallet;privacy;bitcoin;dotnet;nbitcoin;cross-platform;zerolink;wallet;wabisabi;coinjoin;tor</PackageTags>
		<PackageProjectUrl>https://github.com/nopara73/MagicalCryptoWallet/</PackageProjectUrl>
		<PackageLicenseUrl>https://github.com/nopara73/MagicalCryptoWallet/blob/master/LICENSE.md</PackageLicenseUrl>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/nopara73/MagicalCryptoWallet/</RepositoryUrl>
		<ApplicationIcon>Assets\MagicalCryptoWalletLogo.ico</ApplicationIcon>
		<PackageIcon>Assets\MagicalCryptoWalletLogo.ico</PackageIcon>
		<Product>Magical Crypto Wallet</Product>
		<!-- owners is not supported in MSBuild -->
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="ReactiveUI.Avalonia" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\MagicalCryptoWallet.Fluent\MagicalCryptoWallet.Fluent.csproj" />
		<ProjectReference Include="..\MagicalCryptoWallet\MagicalCryptoWallet.csproj" />
	</ItemGroup>

	<ItemGroup>
		<RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />
	</ItemGroup>
</Project>
