<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../MagicalCryptoWallet.Fluent/MagicalCryptoWallet.Fluent.csproj" />
    <PackageReference Include="QRackers" PrivateAssets="all" />
  </ItemGroup>
</Project>
